[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://ometer-back.herokuapp.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200